export const REQUEST_DASHBOARD = 'REQUEST_DASHBOARD';
export const SUCCESS_DASHBOARD = 'SUCCESS_DASHBOARD';
export const FAILURE_DASHBOARD = 'FAILURE_DASHBOARD';
export const CLEAR_DASHBOARD = 'CLEAR_DASHBOARD';